### ISSUE TITLE
Unifying mutable and viewof?

### ISSUE THREAD

**Issue by mbostock** [observablehq/notebook-runtime#142]
What if defining a mutable:

```js
mutable x = 42
```

Were shorthand equivalent to defining a [View](https://beta.observablehq.com/@mbostock/synchronized-views):

```js
viewof x = new View(42)
```

You could still get a mutable’s value reactively as before:

```js
{
  x;
}
```

But now in addition to `mutable x` for non-reactive get and set, you can use `viewof x` as well. This is equivalent to getting `mutable x`:

```js
{
  viewof x.value;
}
```

This is equivalent to setting `mutable x`:

```js
{
  viewof x.value = 43;
}
```

And now you can listen to mutables in the same way you listen to a view:

```js
{
  function changed() {}
  viewof x.addEventListener("input", changed);
  invalidation.then(() => viewof x.removeEventListener("input", changed);
}
```

And you can pass a mutable (container) to a function *etc.*:

```js
function increment(x) {
  ++x.value; // Triggers re-evaluation of anything referencing x!
}
```
```js
{
  increment(viewof x);
}
```

If using `viewof x` when `x` is a mutable is confusing, we could change the get/set behavior of `mutable x` so that it behaves identically to `viewof x`.

/cc @jashkenas

**Comment by jashkenas** [comment]
I've been mulling this over, over the weekend — and I'm still not really sure quite what to think.

On the one hand, it would be lovely to to slim down the standard library to the essentials, and get rid of `mutable` if it's really unnecessary (because views are mutable values already).

On the other hand, at the moment, it feels like `mutable` and `view` are two distinct concepts: One has two different values that reflect underlying data in different ways — the other only has one "value", which can be accessed either reactively, or non-reactively. One is (and feels) wrapped in a container, the other feels like direct access (even if it's wrapped under the hood).

If we do decide to unify the two, using a stdlib `View` class, we should think about our terminology and syntax surrounding the wrapping object, and the reactive and non-reactive facets, to make sure that this feature — which really lies near the heart of the Observable runtime — is as intuitive as we can make it...
